# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fluency' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fluency
pod 'GoogleMLKit/Translate'

  target 'FluencyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FluencyUITests' do
    # Pods for testing
  end

end
